### ISSUE TITLE
Having problems including on my Squarespace blog/site

### ISSUE THREAD

**Issue by bearloga** [joakin/context-cards#1]
This is so super cool! I'd love to start including context cards on my blog posts, especially the technical stats ones. As a test, I'm trying it out on this page: https://mpopov.com/wikipedia-context-cards-test/ but it doesn't seem to work :\

I have the following:

```HTML
<p>
Much of Bayesian statistical inference has been accomplished with the
<a href="#" data-wiki-lang='en' data-wiki-title='Gibbs_sampling'>Gibbs sampler</a>.
</p>
```

(and `<script src="https://unpkg.com/context-cards/dist/bundle.js"></script>` in the header)

Which is then processed by Squarespace and the end result becomes:

```HTML
<p data-preserve-html-node="true">
Much of Bayesian statistical inference has been accomplished with the
<a data-preserve-html-node="true" href="#" data-wiki-lang="en" data-wiki-title="Gibbs_sampling">Gibbs sampler</a>.
</p>
```

Do you know why it's not working – is it because of the extra stuff that Squarespace adds? Do you have any recommendations for getting it to work?

Thanks!

**Comment by joakin** [comment]
Oh whoops!

It is a problem with the library! In the demo the script was after the body so it just happened to work.

I'll look into fixing it and releasing a version, will let you know soon!

**Comment by joakin** [comment]
I've updated the library and published and since you're using the url without version it seems to work!

Check it out @bearloga

**Comment by joakin** [comment]
![screen shot 2018-05-31 at 20 44 09](https://user-images.githubusercontent.com/657839/40801552-76b0f116-6513-11e8-81f7-f4ab81cfaa15.png)

There are some things to fix going forward but it should work fine in modern browsers

**Comment by bearloga** [comment]
Awesome!!! Thank you!
