### ISSUE TITLE
Make gateway endpoint configurable

### ISSUE THREAD

**Issue by PeterTheOne** [joakin/context-cards#2]
For two use cases:

1. To point to a non wikipedia mediawiki
2. and to have some proxy between the website and wikipedia so that the user doesn't request wikipedia directly because of privacy concerns.

**Comment by joakin** [comment]
This project as-is uses the rest services, so pointing to a mediawiki install without the rest endpoints will not work.

The privacy concerns could be a reason to have a proxy, but it could also be a reason for adding an evil proxy that tracks users more than Wikimedia, which is pretty good at privacy and user protection.

I think that if someone needs this with a custom service, they can clone the repo, and change the URL and compile it themselves. I don't think this should be baked in and easy in the library itself.

Thank you for your input.

**Comment by joakin** [comment]
Do you have any examples of wikis with the REST layer deployed?

If there are useful use cases I’m happy to consider adding the feature
sooner.

This is the endpoints needed:
https://en.wikipedia.org/api/rest_v1/

Specifically, /page/summary

Thanks for your input!
