### ISSUE TITLE
Card won't show if article doesn't have a thumbnail

### ISSUE THREAD

**Issue by bearloga** [joakin/context-cards#3]
Hiya! Thanks again for making this awesome library! I started turning some topics into Wikipedia links with previews on my tutorial (https://bearloga.github.io/bayesopt-tutorial-r/):

<img width="978" alt="Screen Shot 2019-04-15 at 10 29 05 AM" src="https://user-images.githubusercontent.com/1807519/56140933-d322f880-5f69-11e9-8fd8-d31088e6840b.png">

I noticed that not all links were working, so I opened up the console and saw that the code expects a `thumbnail` field in the response:

<img width="1204" alt="Screen Shot 2019-04-15 at 10 29 28 AM" src="https://user-images.githubusercontent.com/1807519/56140947-dd44f700-5f69-11e9-858b-dbc991e07a69.png">

P.S. I'm using the latest version of the `context-cards.js`

**Comment by joakin** [comment]
Oh strange! I thought the code handled no thumbnail appropriately.

I’ll have a look when I have a moment!

Thanks for the report and example 👍

**Comment by joakin** [comment]
I've fixed the problem and published 2.0.4 with the fix. Also made a test HTML file here: https://chimeces.com/context-cards/test.html

The unpkg is already updated so if you link to https://unpkg.com/context-cards or https://unpkg.com/context-cards/dist/context-cards.js it should give you https://unpkg.com/context-cards@2.0.4/dist/context-cards.js with the fix if you hard refresh.

**Comment by joakin** [comment]
Thanks for the report BTW!

**Comment by bearloga** [comment]
Thank you so much for such a speedy fix!
