### ISSUE TITLE
should not display on android

### ISSUE THREAD

**Issue by Tejas242** [joakin/context-cards#8]
I am using this package on a website hosted on blogger and the preview work very well but when I open it on an android device and click on any link the preview is also shown there on android. This is too annoying because some cards don't fit the size of android.
So I request you to modify the code or if I am doing something inappropriate please let me know.

**Comment by Tejas242** [comment]
It looks good on android also but must show all previews in vertical mode(i.e. do not show the image on left or right.

**Comment by Tejas242** [comment]
> It looks good on android also thus closing this issue, but must show all previews in vertical mode(i.e. do not show the image on left or right.

**Comment by joakin** [comment]
Hi!

The preview format is dependent on the size of the lead image, if the image is horizontal, the preview will be vertical, if it is a vertical image, then the preview will be horizontal.

Do you think you could share some screenshots of the problems you are having?

Or is it not a problem?

It would be nice if the library worked well on mobile,

Thanks
